// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3VRBebCPIY9kmR3vtqIRe5mnYV_PWx0M',
    appId: '1:727474785846:web:342eb746ef4bd5fa38d297',
    messagingSenderId: '727474785846',
    projectId: 'fir-a062a',
    authDomain: 'fir-a062a.firebaseapp.com',
    storageBucket: 'fir-a062a.appspot.com',
    measurementId: 'G-MESHXXMC56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxdloIscDMyWAgCkus77vZ5jw1IpXDcg8',
    appId: '1:727474785846:android:72d8d60c1a2a841e38d297',
    messagingSenderId: '727474785846',
    projectId: 'fir-a062a',
    storageBucket: 'fir-a062a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL-OmS9LgImTAlgiSPuBKcEZxEwnicCE8',
    appId: '1:727474785846:ios:d099bbcb3acc1fcb38d297',
    messagingSenderId: '727474785846',
    projectId: 'fir-a062a',
    storageBucket: 'fir-a062a.appspot.com',
    androidClientId: '727474785846-uo7hr1jabiunkjla7eataa7dnbi4623o.apps.googleusercontent.com',
    iosClientId: '727474785846-huqm4k9553lsveosj4t88fbu5e2o2dap.apps.googleusercontent.com',
    iosBundleId: 'com.african.chamber.ios',
  );
}
