# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Runner' do
  
    pod 'AFNetworking', '~> 3.0'
    pod 'FBSDKCoreKit', '~> 4.9'

  # Pods for Runner

end
